### ISSUE TITLE
https://github.com/RobloxAPI/rbxfile/tree/v0.2.1

### ISSUE THREAD

**Issue by MarlikAlmighty** [RobloxAPI/rbxfile#10]
Hello, where is "github.com/robloxapi/rbxfile/xml"

**Comment by Anaminus** [comment]
v0.2 has the XML format located in the **rbxlx** subdirectory:

    github.com/robloxapi/rbxfile/rbxlx

Likewise, the binary format is located in the **rbxl** subdirectory:

    github.com/robloxapi/rbxfile/rbxl

**Comment by MarlikAlmighty** [comment]
I am getting this error. When I try to use this package. https://github.com/RobloxAPI/rbxapiref

![изображение](https://user-images.githubusercontent.com/17222940/104827722-06e32e80-5872-11eb-965c-3317c6155230.png)

**Comment by MarlikAlmighty** [comment]
go get ./...

...

go: finding module for package github.com/robloxapi/rbxfile/xml
fetch/config.go:38:2: module github.com/robloxapi/rbxfile@latest found (v0.2.1), but does not contain package github.com/robloxapi/rbxfile/xml

**Comment by Anaminus** [comment]
Make sure `go.mod` is using `github.com/robloxapi/rbxfile v0.1.2` and not `latest`. This is the case for the current version of rbxapiref. If this is also the case in your copy, then it may be a problem with whatever tool you're using.

**Comment by MarlikAlmighty** [comment]
Thank you so much!
